### ISSUE TITLE
dosłownie przepisany kasztanlang

### ISSUE THREAD

**Issue by SoGreeno** [pankoza-pl/cementlang#1]
cementlang:
cement+;
cement-;
cement;

kasztanlang
kasztan+;
kasztan-;
kasztan;

ps. kopiowaniem bardziej sie nie nauczyć programowania :blobthumbsup:

**Comment by whavill** [comment]
@pankoza-pl czy chociaż rozumiesz jakąś linijkę cementlang czy kasztanlang

**Comment by pankoza2-pl** [comment]
tak

**Comment by pankoza2-pl** [comment]
i nie spam maila

**Comment by whavill** [comment]
> i nie spam maila

to wyłącz w ustawieniach. w czym problem.
